databases:
  - name: barber-shop-db
    databaseName: barber_shop
    user: barber_shop_user
    plan: free

services:
  - type: web
    name: barber-shop-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: ./entrypoint.sh
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: barber-shop-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "your-app.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.com,http://localhost:3000"