// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://laglkmgghzngutieivoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZ2xrbWdnaHpuZ3V0aWVpdm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTQwMTcsImV4cCI6MjA3MDczMDAxN30.XnzYO5-uMYjhO1dNI80uVYVW4uRGKMwB5hZluDS3o-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});